### ISSUE TITLE
Unable to run the scan reports on a headless CMS

### ISSUE THREAD

**Issue by mirzaa-atomix** [putyourlightson/craft-sherlock#29]
### Question
We are running this plugin on Craft CMS 3.5.8 and the frontend site is a headless Gatsby site. When running the scans, it outputs the error "Unable to connect to [domain]. Please ensure that the site is reachable and that the system is turned on." 

The site is live, and it is running. Can I know if this plugin is not supporting Headless sites? Or if this is a bug which you can help us on? Thanks in advance

**Comment by bencroker** [comment]
Can you please check for the exact error message in the `storage/logs/sherlock.log` file?

**Comment by mirzaa-atomix** [comment]
Thanks for getting back @bencroker. Reviewing the logs in the above path I found this:

```
2021-04-15 12:46:56 [][1][info] Unable to connect to "https://api.cormie.com.au/". Please ensure that the site is reachable and that the system is turned on.
2021-04-15 12:46:56 [][1][info] Client error: `GET https://api.cormie.com.au/` resulted in a `404 Not Found` response:
{"name":"Not Found","message":"Page not found.","code":0,"status":404}
2021-04-16 10:30:02 [][1][info] Unable to connect to "https://api.cormie.com.au/". Please ensure that the site is reachable and that the system is turned on.
2021-04-16 10:30:02 [][1][info] Client error: `GET https://api.cormie.com.au/` resulted in a `404 Not Found` response:
{"name":"Not Found","message":"Page not found.","code":0,"status":404}
```

Note that since this site is using Craft CMS as the backend, and the frontend in headless Gatsby, the site's frontend and backend are in two domains. I couldn't find a place to update the routes for the report generation on the plugin settings, which I think is the issue. I could be wrong too. Will wait for your response, thanks.

**Comment by bencroker** [comment]
So is the site's base URL set to `https://api.cormie.com.au/`? Does Craft know anything about the front-end site URL?

**Comment by mirzaa-atomix** [comment]
The base URL is set to `https://api.cormie.com.au/` correct, we use the CraftCMS GraphQL API endpoint to source the content in our GatsbyJS frontend site. The frontend domain configurations are all on the `gatsby-config.js` file of the frontend site.

**Comment by bencroker** [comment]
So does Craft know anything about the front-end site URL?

**Comment by mirzaa-atomix** [comment]
Craft CMS does know about the public site, but it's only aware of it via a custom functionality to rewrite the URI's for elements in the admin

**Comment by bencroker** [comment]
Ok I see. Is it standard practice to overwrite all element URL's using a plugin/module? I'm thinking about the best way to make this possible in Sherlock and knowing more about how URLs are managed in Gatsby sites powered by Craft.

**Comment by jackatomix** [comment]
@bencroker I can chime in here. When I implemented this code I looked into it there didn't seem to be a great way for you to specify the frontend link for elements in Craft CMS, which did seem odd at the time seeing as headless mode had just been officially released. This might have changed since then, but a quick search didn't seem to reveal anything.

In an attempt to make things a little easier for our content team I implemented some rudimentary functionality within our installation that would update the element uri based on some pretty fragile conditions:

```php
        Event::on(
            Element::class,
            Element::EVENT_INIT,
            function (Event $event) {
                $request = Craft::$app->getRequest();
                if ($request->isConsoleRequest) {
                    return;
                }

                /** @var Element $element */
                $element = $event->sender;
                $controller = Craft::$app->controller;

                $isShoppingFeedRequest = $request->getFullPath() === trim(GoogleShoppingFeed::getInstance()->getSettings()->shoppingFeed, '/');
                if (!$request->isCpRequest && !$isShoppingFeedRequest) {
                    return;
                }

                $isGet = $request->getIsGet();
                if (!$isGet && $controller) {
                    $isGet = $controller->action->id === 'get-elements';
                }

                if (!$isGet) {
                    return;
                }

                if ($element->uri && !UrlHelper::isAbsoluteUrl($element->uri)) {
                    $root = Craft::$app->getConfig()->getGeneral()->publicRoot;
                    $element->uri = sprintf("%s%s", $root ?? '/', $element->getIsHomepage() ? '' : $element->uri);
                }
            }
        );
```

As you can see this is not exactly the most elegant solution, but our new `publicRoot` config option worked fine for our use case.

Regarding routing; in our particular case Gatsby is configured to use the path defined by the source (Craft) as the path to output, but there is no requirement for that to be the case in every Gatsby site so you can't really assume it will be.

**Comment by bencroker** [comment]
Thanks for the explanation @jackatomix. There appears to still not be a standard way to set the static site URL in a headless Craft setup. Rather than try to hack this into the plugin as a site URL override, I've asked to see whether this is something that Craft might make easier in future. Will report back when there's an update.

**Comment by bencroker** [comment]
@jackatomix have you considered setting the site's base URL to `https://www.cormie.com.au/` and the GraphQL route to an absolute URL?

#### `config/routes.php`
```php
return [
    'api' => 'https://api.cormie.com.au/',
    // ...
];
```

**Comment by bencroker** [comment]
Closing due to inactivity.
